// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLS4WTMK3rDiR5Fd7Ocbqrh14X6enGFf4',
    appId: '1:1026624818994:web:99afa2a5e182fc72ed112b',
    messagingSenderId: '1026624818994',
    projectId: 'school-management-applic-42008',
    authDomain: 'school-management-applic-42008.firebaseapp.com',
    storageBucket: 'school-management-applic-42008.firebasestorage.app',
    measurementId: 'G-VZTBWQXXHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB345hSBBTa8gtpWAwyqfi7qI7qO_M5hAo',
    appId: '1:1026624818994:android:33910095486e4f16ed112b',
    messagingSenderId: '1026624818994',
    projectId: 'school-management-applic-42008',
    storageBucket: 'school-management-applic-42008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEm9H4XW3VOysEl6ZObQdEx_FMOUoP1u4',
    appId: '1:1026624818994:ios:9a7568dac9cfaa82ed112b',
    messagingSenderId: '1026624818994',
    projectId: 'school-management-applic-42008',
    storageBucket: 'school-management-applic-42008.firebasestorage.app',
    iosBundleId: 'com.educonnect.educonnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEm9H4XW3VOysEl6ZObQdEx_FMOUoP1u4',
    appId: '1:1026624818994:ios:9a7568dac9cfaa82ed112b',
    messagingSenderId: '1026624818994',
    projectId: 'school-management-applic-42008',
    storageBucket: 'school-management-applic-42008.firebasestorage.app',
    iosBundleId: 'com.educonnect.educonnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLS4WTMK3rDiR5Fd7Ocbqrh14X6enGFf4',
    appId: '1:1026624818994:web:fecae7417d93e0efed112b',
    messagingSenderId: '1026624818994',
    projectId: 'school-management-applic-42008',
    authDomain: 'school-management-applic-42008.firebaseapp.com',
    storageBucket: 'school-management-applic-42008.firebasestorage.app',
    measurementId: 'G-5EZ6YY5TR5',
  );
}
